### ISSUE TITLE
Player leave scheduled restart instantly restarting upon join.

### ISSUE THREAD

**Issue by CoinSkipper** [Steveplays28/restart-server#14]
I am currently running a Fabric MC 1.19.2 server with a few server + client side mods. When the variable: "restartIfNoPlayersHaveBeenOnline" is set to true, whenever a player attempts to join the server, they are greeted with: "Server is restarting...". This will happen regardless of the time that the variable: "noPlayersWaitTime" is set to. I have reinstalled the config to its defaults, and the server is joinable, but as soon as the "restartIfNoPlayersHaveBeenOnline" variable is set to true, it restarts upon a join attempt. 

I have tried to tweak the times and settings for a verity of the scheduled restarts, but none seem to effect it except for the one mentioned above.

**Comment by Steveplays28** [comment]
I'll investigate sometime these weeks. Quite busy with exams so please do give me quite a bit to take a look.
Thanks for the report!

**Comment by CoinSkipper** [comment]
All good! Totally understand, good luck and take your time!

**Comment by Steveplays28** [comment]
Thanks, appreciate it!

**Comment by Steveplays28** [comment]
Fixed by 1d01b02c882d53a33f7ee484c301f5b341a7cbf4, will release in `v1.1.1`!

**Comment by Steveplays28** [comment]
Released in [`v1.1.1`](https://github.com/Steveplays28/restart-server/milestone/2)!
Download on Modrinth for [1.18.x](https://modrinth.com/mod/restart-server/version/1.1.1+mc1.18.x) and [1.19.x-1.20.x](https://modrinth.com/mod/restart-server/version/1.1.1+mc1.19.x-1.20.x).

**Comment by CoinSkipper** [comment]
Thank you!
