### ISSUE TITLE
Incompatible with luckperms

### ISSUE THREAD

**Issue by vipaoL** [Steveplays28/restart-server#16]
I want to give permission to restart the server to moderators, but it seems like this mod doesn't support it. It isn't shown by autocomplete in luckperms' web editor.
![screenshot](https://github.com/Steveplays28/restart-server/assets/59665125/0d385005-1644-464f-9fa0-0f3826988af2)
![screenshot](https://github.com/Steveplays28/restart-server/assets/59665125/3058a0f4-fe1d-4a80-9a29-b503733bc48f)
I tried to write something like "restartserver.commands.restart" manually, but it doesn't work.

As an example of mod which support privileges:
https://github.com/Patbox/ArmorStandEditor/blob/1.20/src/main/java/eu/pb4/armorstandeditor/util/GeneralCommands.java

**Comment by Steveplays28** [comment]
Ah, I see. I need to add `.requires()` to the command, I can add that.

**Comment by Steveplays28** [comment]
Fixed in `v1.2.0`, thanks to @arnokeesman!

You can download the new version here:
- https://modrinth.com/mod/restart-server
- https://curseforge.com/minecraft/mc-mods/restart-server
- https://github.com/Steveplays28/restart-server/releases/latest
