### ISSUE TITLE
Update 1.20.1

### ISSUE THREAD

**Issue by xMathayus** [Steveplays28/restart-server#19]
Do you happen to have any future updates for 1.20.1?

**Comment by Steveplays28** [comment]
I can update the mod sometime, give me a few days.
Thanks for checking it out.

**Comment by Steveplays28** [comment]
Done, you can download the mod for `1.20.x` here:
- [GitHub](https://github.com/Steveplays28/restart-server/releases/latest)
- [Modrinth](https://modrinth.com/mod/restart-server)
- [CurseForge](https://www.curseforge.com/minecraft/mc-mods/restart-server)
