### ISSUE TITLE
Please make it possible to use with lower op permission levels, or without op

### ISSUE THREAD

**Issue by cristianassis** [Steveplays28/restart-server#23]
I wanted to give the permission for players in my server that I trust and I can't give them op that allows tp and creative mode, I just wanted to give them the control if the server lags

**Comment by Steveplays28** [comment]
Fabric Permissions API (and by extension LuckPerms) is supported.
There's a permission node (`restart_server.commands.restart`) you can give players access to, so they can run the command.
