### ISSUE TITLE
Support for scripts that automatically restart on server stop

### ISSUE THREAD

**Issue by jschenke488** [Steveplays28/restart-server#3]
Add a config option to just run /stop instead of specifying a file name for scripts such as the autorestart script from https://startmc.sh/ 
While this wouldn't be any different than running /stop for manual restarts, it would work for scheduled restarts

**Comment by Steveplays28** [comment]
Very good suggestion, I'll see when I have time to implement this, as well as the other issues.
Probably going to be the weekend.
