### ISSUE TITLE
[Enhancement] Restart Countdown

### ISSUE THREAD

**Issue by ghost** [Steveplays28/restart-server#6]
Configurable countdown of the last X seconds before the server actually performs the restart. Seems better than just saying "restarting in ~2m".

Furthermore, instead of a restart message like `"restarting in ~2m"`, it would be better if you could use a placeholder to specify where the total restart grace period is displayed. Something like `"restarting in ~${time}", for a basic example. This would work better alongside the above suggestion of a configurable timer, as the timer message could also be configured dynamically using a similar placeholder.

**Comment by Steveplays28** [comment]
I was planning to make this configurable for the next release as well, thanks for opening an issue.

Can you tell me more about dynamically configuring the time using placeholders though?
I don't see the point, since you can just test how long your server takes to restart on average, and put that in the `restartMessage` in the config.
Sorry if I'm not understanding correctly (again).

**Comment by ghost** [comment]
> I don't see the point, since you can just test how long your server takes to restart on average, and put that in the `restartMessage` in the config.

The miscommunication here is that you're talking about the actual time the server takes to restart, whereas I'm talking about the grace period before the restart initiates. I see little point in trying to tell people how long it's going to take for the server to restart, given that is such an arbitrary value and most people will misinterpret it as the grace period anyway.

**Comment by ghost** [comment]
> Sorry if I'm not understanding correctly (again).

Hey no it's fine! I don't mind clarifying :)

**Comment by Steveplays28** [comment]
> > I don't see the point, since you can just test how long your server takes to restart on average, and put that in the `restartMessage` in the config.
> 
> The miscommunication here is that you're talking about the actual time the server takes to restart, whereas I'm talking about the grace period before the restart initiates. I see little point in trying to tell people how long it's going to take for the server to restart, given that is such an arbitrary value and most people will misinterpret it as the grace period anyway.

Ah right, I see what you mean now.
I will definitely implement a placeholder like that (and document it).

Thanks!
