### ISSUE TITLE
1.18 doesn't work

### ISSUE THREAD

**Issue by arnokeesman** [Steveplays28/restart-server#8]
Releases of the mod say it works on 1.18.x and 1.19.x and so does `fabric.mod.json` but it just doesn't on 1.18.
I know the README says you won't backport so it'd just be nice if you could remove the apparent support for 1.18.
There's a backport of the dev branch for 1.18.2 on my fork (doesn't work on 1.19), just let me know if you want a PR for it.

**Comment by Steveplays28** [comment]
A PR would be amazing!
I'll take a look sometime these few weeks. Could you send log files of the error that happens on 1.18 as well?

**Comment by arnokeesman** [comment]
[logs](https://mclo.gs/oibXEO9) (1.18,2)
The problem is that you're using fabric.api.command.v2 to register the command, this doesn't exist for versions below 1.19

**Comment by Steveplays28** [comment]
Ahh, makes sense. Thank you.

**Comment by Steveplays28** [comment]
Will upload the new build once I'm able to log into Modrinth again. Opened a ticket, it's apparently due to me having so many notifications that the backend bugs, haha.
I can confirm everything works though, even wrote a small gametest to verify basic functionality.
